import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { GlobalStyles } from "@mui/material";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <GlobalStyles
            styles={{
              html: {
                margin: 0,
                padding: 0,
                boxSizing: "border-box",
                height: "100%",
              },
              body: {
                margin: 0,
                padding: 0,
                boxSizing: "inherit",
                height: "100%",
                backgroundColor: "#7A89C2",
              },
              "*": {
                boxSizing: "inherit",
              },
            }}
          />
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
